version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - comic-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: comic-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - comic-network
    environment:
      - MONGO_URL=mongodb://mongo:27017/comicsDB  # 可依需求修改 DB 名稱

networks:
  comic-network:
    driver: bridge

volumes:
  mongo_data:
